# Generated by Django 5.0.4 on 2024-04-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="укажите ссылку на оплату",
                max_length=512,
                null=True,
                verbose_name="ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="sessions_id",
            field=models.CharField(
                blank=True,
                help_text="укажите id сессии",
                max_length=64,
                null=True,
                verbose_name="id сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="сумма оплаты"),
        ),
    ]
