# Generated by Django 5.0.4 on 2024-04-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="sessions_id",
            field=models.CharField(
                blank=True,
                help_text="укажите id сессии",
                max_length=512,
                null=True,
                verbose_name="id сессии",
            ),
        ),
    ]
