# Generated by Django 5.0.4 on 2024-04-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_coursesubscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursesubscription",
            old_name="users",
            new_name="user",
        ),
    ]
