# Generated by Django 5.0.4 on 2024-04-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_rename_users_coursesubscription_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("name",),
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
            },
        ),
    ]
