# Generated by Django 5.0.4 on 2024-04-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_alter_course_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("name",),
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="video_lesson", verbose_name="видео"
            ),
        ),
    ]
